export const FavoriteProductAction = {
  GET_FAVORITE_PRODUCT: "GET_FAVORITE_PRODUCT",
  ADD_FAVORITE_PRODUCT: "ADD_FAVORITE_PRODUCT",
  REMOVE_FAVORITE_PRODUCT: "REMOVE_FAVORITE_PRODUCT",
  ERROR: "ERROR",
};
